# Generated by Django 4.2.1 on 2023-11-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriScanApp', '0002_aboutus_contactus_service_delete_dashboarditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='ContactUs',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
